<?php

/**
 * This is the model base class for the table "{{tuk_research_grant_expenditure}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "grantexpenditureform".
 *
 * Columns in table "{{tuk_research_grant_expenditure}}" available as properties of the model,
 * followed by relations of table "{{tuk_research_grant_expenditure}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $project_code
 * @property string $expenditure_description
 * @property string $amount
 * @property string $date
 * @property string $currency
 * @property integer $grant_id
 *
 * @property TukResearchGrant $projectCode
 */
abstract class Basegrantexpenditureform extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{tuk_research_grant_expenditure}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'grantexpenditureform|grantexpenditureforms', $n);
	}

	public static function representingColumn() {
		return 'expenditure_description';
	}

	public function rules() {
		return array(
			array('project_code, expenditure_description, amount', 'required'),
			array('grant_id', 'numerical', 'integerOnly'=>true),
			array('project_code, amount', 'length', 'max'=>100),
			array('expenditure_description', 'length', 'max'=>225),
			array('date, currency', 'length', 'max'=>30),
			array('date, currency, grant_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, project_code, expenditure_description, amount, date, currency, grant_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'projectCode' => array(self::BELONGS_TO, 'TukResearchGrant', 'project_code'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'project_code' => null,
			'expenditure_description' => Yii::t('app', 'Expenditure Description'),
			'amount' => Yii::t('app', 'Amount'),
			'date' => Yii::t('app', 'Date'),
			'currency' => Yii::t('app', 'Currency'),
			'grant_id' => Yii::t('app', 'Grant'),
			'projectCode' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('project_code', $this->project_code);
		$criteria->compare('expenditure_description', $this->expenditure_description, true);
		$criteria->compare('amount', $this->amount, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('currency', $this->currency, true);
		$criteria->compare('grant_id', $this->grant_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}