<?php

/**
 * This is the model base class for the table "{{tuk_research_grant_balance}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "grantbalance".
 *
 * Columns in table "{{tuk_research_grant_balance}}" available as properties of the model,
 * followed by relations of table "{{tuk_research_grant_balance}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $project_code
 * @property string $total_revenue
 * @property string $total_expenditure
 * @property string $remaining_balance
 * @property string $date
 * @property integer $revenue_id
 * @property integer $expenditure_id
 *
 * @property TukResearchGrantExpenditure1 $id0
 * @property TukResearchGrant1 $projectCode
 */
abstract class Basegrantbalance extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{tuk_research_grant_balance}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'grantbalance|grantbalances', $n);
	}

	public static function representingColumn() {
		return 'project_code';
	}

	public function rules() {
		return array(
			array('project_code', 'required'),
			array('revenue_id, expenditure_id', 'numerical', 'integerOnly'=>true),
			array('project_code, total_revenue, total_expenditure, remaining_balance', 'length', 'max'=>100),
			array('date', 'length', 'max'=>30),
			array('total_revenue, total_expenditure, remaining_balance, date, revenue_id, expenditure_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, project_code, total_revenue, total_expenditure, remaining_balance, date, revenue_id, expenditure_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'project_code' => array(self::BELONGS_TO, 'tukgrant1', 'project_code'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => null,
			'project_code' => Yii::t('app', 'Project Code'),
			'total_revenue' => Yii::t('app', 'Total Revenue'),
			'total_expenditure' => Yii::t('app', 'Total Expenditure'),
			'remaining_balance' => Yii::t('app', 'Remaining Balance'),
			'date' => Yii::t('app', 'Date'),
			'revenue_id' => Yii::t('app', 'Revenue'),
			'expenditure_id' => Yii::t('app', 'Expenditure'),
			'id0' => null,
			'projectCode' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('project_code', $this->project_code);
		$criteria->compare('total_revenue', $this->total_revenue, true);
		$criteria->compare('total_expenditure', $this->total_expenditure, true);
		$criteria->compare('remaining_balance', $this->remaining_balance, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('revenue_id', $this->revenue_id);
		$criteria->compare('expenditure_id', $this->expenditure_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}