<?php

/**
 * This is the model base class for the table "{{tuk_research_grant1}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tukgrant1".
 *
 * Columns in table "{{tuk_research_grant1}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $project_name
 * @property string $project_code
 * @property string $project_financier
 * @property string $patner_institution
 * @property string $project_coodinator
 * @property string $institution_coordinator
 * @property string $program_year
 * @property string $period
 * @property string $account_number
 * @property string $currency_disbursed
 *
 */
abstract class BaseTukgrant1 extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{tuk_research_grant}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tukgrant1|Tukgrant1s', $n);
	}

	public static function representingColumn() {
		return 'project_name';
	}

	public function rules() {
		return array(
			array('project_name, project_code, project_financier, patner_institution, project_coodinator, institution_coordinator, program_year, period, account_number, currency_disbursed', 'required'),
			array('project_name, project_code, project_financier, patner_institution, project_coodinator, institution_coordinator, program_year, period, account_number, currency_disbursed', 'length', 'max'=>100),
			array('id, project_name, project_code, project_financier, patner_institution, project_coodinator, institution_coordinator, program_year, period, account_number, currency_disbursed', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'project_name' => Yii::t('app', 'Project Name'),
			'project_code' => Yii::t('app', 'Project Code'),
			'project_financier' => Yii::t('app', 'Project Financier'),
			'patner_institution' => Yii::t('app', 'Patner Institution'),
			'project_coodinator' => Yii::t('app', 'Project Coodinator'),
			'institution_coordinator' => Yii::t('app', 'Institution Coordinator'),
			'program_year' => Yii::t('app', 'Program Year'),
			'period' => Yii::t('app', 'Period'),
			'account_number' => Yii::t('app', 'Account Number'),
			'currency_disbursed' => Yii::t('app', 'Currency Disbursed'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('project_name', $this->project_name, true);
		$criteria->compare('project_code', $this->project_code, true);
		$criteria->compare('project_financier', $this->project_financier, true);
		$criteria->compare('patner_institution', $this->patner_institution, true);
		$criteria->compare('project_coodinator', $this->project_coodinator, true);
		$criteria->compare('institution_coordinator', $this->institution_coordinator, true);
		$criteria->compare('program_year', $this->program_year, true);
		$criteria->compare('period', $this->period, true);
		$criteria->compare('account_number', $this->account_number, true);
		$criteria->compare('currency_disbursed', $this->currency_disbursed, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}